build:
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --verbose --coverage-clover ./build/logs/coverage.clover tests/
            coverage:
              file: ./build/logs/coverage.clover   
              format: clover