language: php
php:
  - 7.1
cache:
  directories:
  - ~/.composer/cache
before_install:
  - composer self-update
install:
  - composer clear-cache
  - composer install --prefer-source
script:
  - ./vendor/bin/phpcs --standard=psr12 src/
  - ./vendor/bin/phpunit --verbose --coverage-clover ./build/logs/coverage.clover tests/
after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/coverage.clover